version: '3.9'
services:
  db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    
  
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - uploads_volume:/usr/share/nginx/html/uploads
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    environment: 
      FLASK_APP: app.py
      JWT_SECRET_KEY: your_secret_key_here  # Clave secreta para generar JWT
    volumes:
      - ./backend:/app         # bind mount (correcto)
      - uploads_volume:/app/uploads
    depends_on:
      - db

volumes:
  db_data:
  uploads_volume:


